### ISSUE TITLE
[Request] 请添加 .editorconfig 文件

### ISSUE THREAD

**Issue by plox3770** [serrer6/DynlantRD#2]
我知道这可能没什么用，但是我仍然需要 .editorconfig 文件，这可以帮助我这种使用Tab缩进的异类解放双手。
以下是一个示例，我尽量使它符合此项目目前的规范。
```
root = true

[*]
indent_style = space
indent_size = 2
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.html]
indent_size = 4
```
此示例可能使 .md 文件结尾空格被删除，如果需要请在结尾添加此段。
```
[*.md]
trim_trailing_whitespace = false
```

**Comment by serrer6** [comment]
嗯，EditorConfig确实有助于项目的规范化
我尝试将它添加进项目中

> 你提出的新请求很不错，plox3770

**Comment by serrer6** [comment]
@plox3770 按照您的想法，我编写了 .editorconfig

```
root = true

[*]
indent_style = space
end_of_line = lf
charset = utf-8
indent_size = 2

[*.css]
indent_size = 2

[*.md]
trim_trailing_whitespace = false
```
>我认为它仍有很多缺点，所以我想邀请它对他进行改进。虽然目前项目中没有存在CSS文件，但我仍想预先设置

**Comment by serrer6** [comment]
我阅读了您的提示和建议，并且查阅了一些有关资料

1. webpack.common.js 稍后会整理
2. 按照您的建议做以下修改：
```
root = true

[*]
indent_style = tab
tab_width = 4
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
spaces_around_operators = true
curly_bracket_next_line = true

[*.css]
tab_width = 2

[*.{js,html,css}]
quote_type = double

[*.md]
trim_trailing_whitespace = false
```

> 我很少使用editorconfig，对可配置的项目生疏

**Comment by serrer6** [comment]
我认为保留`spaces_around_operators` & `curly_bracket_next_line` & `quote_type`并不会使那些不支持的 编辑器/插件 出现致命问题。且在使用支持这些属性的编辑器时，可以使代码更佳规范。

> git://test/index.html在一开始被添加进项目之中，没有发生任何改变。我或许应该重构它。

**Comment by serrer6** [comment]
很抱歉，回复较晚
感谢您提出新的项目建议

> 我很高兴与您谈论这么多，plox3770
