### ISSUE TITLE
[Request] 重写 docs 到 Github 项目 Wiki

### ISSUE THREAD

**Issue by plox3770** [serrer6/DynlantRD#5]
我认为使用 Github 自带的 Wiki 相对于手动维护一个 .md 文件作为列表更加容易，且以硬链接组织文档间关系的形式并不利于后期的文档维护。

> 这并非重要提议，可以稍后处理或者直接 Close issue 。

**Comment by serrer6** [comment]
我收到了您的反馈
我或许可以抽时间在Github Pages上部署VuePress渲染的文档

> Github Pages + VuePress相比Github Wiki更好，且对某些DNS污染严重地区在绝大多数时候可以提供比Github Wiki更稳定的连接（且访问速度相差不大）
